services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend-nginx
    ports:
      - "3000:80"
    environment:
      NODE_ENV: production
    restart: unless-stopped
